config {
    type: "test",
    dataset: "raw_mes_prd_order"
}

input {
    name: "mes_production_order",
    data: [
        {order_id: "order1", product_serial_no: "serial1"},
        {order_id: "order2", product_serial_no: "serial2"},
        {order_id: "order3", product_serial_no: "serial3"},
        {order_id: "order4", product_serial_no: "serial4"},
        {order_id: "order5", product_serial_no: "serial5"}
    ]
}

SELECT
    "order1" AS order_id, "serial1" AS product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
    "order2" AS order_id, "serial2" AS product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
    "order3" AS order_id, "serial3" AS product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
    "order4" AS order_id, "serial4" AS product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
    "order5" AS order_id, "serial5" AS product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
