config {
  type: "test",
  dataset: "raw_iot_cnc_telemetry"
}

input "cnc_machine_telemetry" {
  SELECT 'C-1' AS machine_id, '2023-01-01 00:00:00' AS timestamp, '{"temp": 25.5}' AS payload UNION ALL
  SELECT 'C-1' AS machine_id, '2023-01-01 00:00:01' AS timestamp, '{"temp": 25.6}' AS payload UNION ALL
  SELECT 'C-2' AS machine_id, '2023-01-01 00:00:00' AS timestamp, '{"temp": 30.1}' AS payload UNION ALL
  SELECT 'C-1' AS machine_id, '2023-01-01 00:00:02' AS timestamp, '{"temp": 25.7}' AS payload UNION ALL
  SELECT 'C-2' AS machine_id, '2023-01-01 00:00:01' AS timestamp, '{"temp": 30.2}' AS payload
}

SELECT 'C-1' AS machine_id, '2023-01-01 00:00:00' AS timestamp, '{"temp": 25.5}' AS payload, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date UNION ALL
SELECT 'C-1' AS machine_id, '2023-01-01 00:00:01' AS timestamp, '{"temp": 25.6}' AS payload, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date UNION ALL
SELECT 'C-2' AS machine_id, '2023-01-01 00:00:00' AS timestamp, '{"temp": 30.1}' AS payload, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date UNION ALL
SELECT 'C-1' AS machine_id, '2023-01-01 00:00:02' AS timestamp, '{"temp": 25.7}' AS payload, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date UNION ALL
SELECT 'C-2' AS machine_id, '2023-01-01 00:00:01' AS timestamp, '{"temp": 30.2}' AS payload, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
