config {
  type: "test",
  dataset: "raw_mes_prd_order"
}

input "mes_production_order" {
  SELECT 'order1' as order_id, 'psn1' as product_serial_no UNION ALL
  SELECT 'order2' as order_id, 'psn2' as product_serial_no UNION ALL
  SELECT 'order3' as order_id, 'psn3' as product_serial_no UNION ALL
  SELECT 'order4' as order_id, 'psn4' as product_serial_no UNION ALL
  SELECT 'order5' as order_id, 'psn5' as product_serial_no
}

  SELECT 'order1' as order_id, 'psn1' as product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date UNION ALL
  SELECT 'order2' as order_id, 'psn2' as product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date UNION ALL
  SELECT 'order3' as order_id, 'psn3' as product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date UNION ALL
  SELECT 'order4' as order_id, 'psn4' as product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date UNION ALL
  SELECT 'order5' as order_id, 'psn5' as product_serial_no, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
