config {
  type: "test",
  dataset: "raw_erp_mat_master"
}

input "erp_material_master" {
  SELECT 'mat1' AS material_id, 'Material 1' AS material_name UNION ALL
  SELECT 'mat2' AS material_id, 'Material 2' AS material_name UNION ALL
  SELECT 'mat3' AS material_id, 'Material 3' AS material_name UNION ALL
  SELECT 'mat4' AS material_id, 'Material 4' AS material_name UNION ALL
  SELECT 'mat5' AS material_id, 'Material 5' AS material_name
}

SELECT
  'mat1' AS material_id, 'Material 1' AS material_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
  'mat2' AS material_id, 'Material 2' AS material_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
  'mat3' AS material_id, 'Material 3' AS material_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
  'mat4' AS material_id, 'Material 4' AS material_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
  'mat5' AS material_id, 'Material 5' AS material_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date