config {
  type: "test",
  dataset: "raw_erp_worker_master"
}

input "erp_worker_master" {
  SELECT 'w1' AS worker_id, 'Worker 1' AS worker_name UNION ALL
  SELECT 'w2' AS worker_id, 'Worker 2' AS worker_name UNION ALL
  SELECT 'w3' AS worker_id, 'Worker 3' AS worker_name UNION ALL
  SELECT 'w4' AS worker_id, 'Worker 4' AS worker_name UNION ALL
  SELECT 'w5' AS worker_id, 'Worker 5' AS worker_name
}

SELECT
  'w1' AS worker_id, 'Worker 1' AS worker_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
  'w2' AS worker_id, 'Worker 2' AS worker_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
  'w3' AS worker_id, 'Worker 3' AS worker_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
  'w4' AS worker_id, 'Worker 4' AS worker_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date
UNION ALL
SELECT
  'w5' AS worker_id, 'Worker 5' AS worker_name, TIMESTAMP(CURRENT_DATE()) AS etl_loaded_at, CURRENT_DATE() AS etl_loaded_date