config {
  type: "table",
  schema: "dev_dataform_dataset",
  name: "tmp_iot_cnc_resampled",
  tags: ["processed"],
  bigquery: {
    partitionBy: "telemetry_date",
    clusterBy: ["machine_id"]
  }
}

WITH Step1_Expanded AS (
  SELECT
    machine_id,
    timestamp AS telemetry_timestamp,
    DATE(timestamp) as telemetry_date,
    SAFE_CAST(JSON_VALUE(payload, '$.temperature') AS FLOAT64) AS temperature,
    SAFE_CAST(JSON_VALUE(payload, '$.vibration') AS FLOAT64) AS vibration
  FROM
    ${ref("raw_iot_cnc_telemetry")}
),
Step2_Filtered AS (
  SELECT
    *
  FROM
    Step1_Expanded
  -- Placeholder for outlier removal logic. For example, remove temps > 1000.
  WHERE
    temperature < 1000
)
-- Step3: Downsampling to 1-second average
SELECT
  machine_id,
  TIMESTAMP_TRUNC(telemetry_timestamp, SECOND) as telemetry_timestamp,
  AVG(temperature) AS temperature,
  AVG(vibration) AS vibration
FROM
  Step2_Filtered
GROUP BY
  1, 2
HAVING
  machine_id IS NOT NULL AND telemetry_timestamp IS NOT NULL