config {
  type: "table",
  schema: "dev_dataform_dataset",
  name: "tmp_erp_worker_master_scd2",
  bigquery: {
    clusterBy: ["worker_id"]
  }
}

-- This table creates a Type 2 Slowly Changing Dimension for the worker master.
-- It tracks the history of changes and anonymizes personal data.

WITH ranked_changes AS (
  SELECT
    *,
    LEAD(etl_loaded_at, 1, TIMESTAMP('9999-12-31 23:59:59')) OVER (PARTITION BY worker_id ORDER BY etl_loaded_at) as next_load_time
  FROM
    ${ref("raw_erp_worker_master")}
)
SELECT
  -- Anonymize personal data
  SHA256(worker_id) as worker_id,
  '-- Anonymized --' as worker_name,
  department,
  -- other attributes
  etl_loaded_at AS valid_from,
  next_load_time AS valid_to,
  (next_load_time = TIMESTAMP('9999-12-31 23:59:59')) AS is_current
FROM
  ranked_changes
