config {
  type: "table",
  schema: "dev_dataform_dataset",
  name: "tmp_erp_worker_master_scd2",
  bigquery: {
    clusterBy: ["worker_id"]
  }
}

SELECT
  worker_id,
  name,
  etl_loaded_at AS valid_from,
  LEAD(etl_loaded_at, 1, TIMESTAMP('9999-12-31 23:59:59')) OVER (PARTITION BY worker_id ORDER BY etl_loaded_at) AS valid_to,
  (LEAD(etl_loaded_at, 1) OVER (PARTITION BY worker_id ORDER BY etl_loaded_at)) IS NULL AS is_current
FROM
  ${ref("raw_erp_worker_master")}
