config {
    type: "table",
    schema: "dev_dataform_dataset",
    name: "tmp_mes_prd_order_cleansed",
    partition_by: "production_date",
    cluster_by: ["product_serial_no"]
}

SELECT
    order_id,
    product_serial_no,
    CAST(start_time_str AS TIMESTAMP) AS start_time,
    CAST(end_time_str AS TIMESTAMP) AS end_time,
    -- Assuming production_date is derived from start_time
    DATE(CAST(start_time_str AS TIMESTAMP)) as production_date,
    NORMALIZE(order_id, NFKC) as order_id_normalized,
    COALESCE(work_memo, '') as work_memo
FROM
    ${ref("raw_mes_prd_order")}
