config {
  type: "test",
  dataset: "stg_products"
}

input "raw_products" {
  SELECT 1 AS product_id, 10.0 AS price UNION ALL
  SELECT 1 AS product_id, 20.0 AS price UNION ALL
  SELECT 2 AS product_id, 30.0 AS price UNION ALL
  SELECT 2 AS product_id, 40.0 AS price
}

SELECT
  1 AS product_id, 30.0 AS total_price, 2 AS record_count, 15.0 AS average_price, 10.0 AS min_price, 20.0 AS max_price UNION ALL
SELECT
  2 AS product_id, 70.0 AS total_price, 2 AS record_count, 35.0 AS average_price, 30.0 AS min_price, 40.0 AS max_price
