config {
  type: "test",
  dataset: "stg_products"
}

input "raw_products" {
  SELECT 1 AS product_id, 10.0 AS price UNION ALL
  SELECT 2 AS product_id, 25.0 AS price UNION ALL
  SELECT 3 AS product_id, 30.0 AS price UNION ALL
  SELECT 4 AS product_id, 45.0 AS price UNION ALL
  SELECT 5 AS product_id, 50.0 AS price
}

SELECT
  1600.0 AS total_price,
  5     AS record_count,
  32.0  AS average_price,
  10.0  AS min_price,
  50.0  AS max_price
