config {
  type: "test",
  dataset: "dim_worker"
}

-- NOTE: mock data designed for deterministic JOIN results
input "tmp_erp_worker_master_scd2" {
  SELECT 'w1_hash' as worker_id, 'w1' as worker_name, 'Dept A' as department, false as is_current UNION ALL
  SELECT 'w1_hash' as worker_id, 'w1' as worker_name, 'Dept B' as department, true as is_current UNION ALL
  SELECT 'w2_hash' as worker_id, 'w2' as worker_name, 'Dept C' as department, true as is_current
}

SELECT
  'w1_hash' as worker_id, 'w1' as worker_name, 'Dept B' as department
UNION ALL
SELECT
  'w2_hash' as worker_id, 'w2' as worker_name, 'Dept C' as department
