config {
    type: "table",
    schema: "dev_dataform_dataset",
    name: "fct_equipment_downtime",
    partition_by: "status_date",
    cluster_by: ["equipment_id", "status_code"]
}

SELECT
    status.*,
    prod.order_id,
    prod.product_serial_no
FROM
    ${ref("tmp_mes_eq_status_agg")} AS status
LEFT JOIN
    ${ref("fct_production_performance")} AS prod
    ON status.equipment_id = prod.equipment_id
    -- 状態発生時刻が製造実績の「開始時刻〜終了時刻の間に収まる（BETWEEN）」条件で LEFT JOIN
    AND status.status_changed_at BETWEEN prod.start_time AND prod.end_time
