config {
  type: "table",
  schema: "dev_dataform_dataset",
  name: "fct_quality_inspection",
  bigquery: {
    partitionBy: "inspection_date",
    clusterBy: ["product_serial_no"]
  }
}

-- This fact table enriches quality inspection results with production performance data.
SELECT
  qual.inspection_id,
  qual.product_serial_no,
  qual.inspection_date,
  qual.measurement_value_cm,
  -- Columns from fct_production_performance
  prod.order_id,
  prod.production_lead_time_seconds,
  prod.material_id,
  prod.worker_id
FROM ${ref("tmp_qms_inspection_std")} AS qual
LEFT JOIN ${ref("fct_production_performance")} AS prod
  ON qual.product_serial_no = prod.product_serial_no
