config {
  type: "table",
  schema: "dev_dataform_dataset",
  name: "fct_machine_sensor",
  bigquery: {
    partitionBy: "telemetry_date",
    clusterBy: ["product_serial_no", "machine_id"]
  }
}

-- This fact table links machine sensor data with the product serial number being processed at that time.
SELECT
  sensor.machine_id,
  sensor.telemetry_timestamp,
  sensor.telemetry_date,
  sensor.temperature,
  sensor.vibration,
  prod.product_serial_no
FROM ${ref("tmp_iot_cnc_resampled")} AS sensor
LEFT JOIN ${ref("fct_production_performance")} AS prod
  ON sensor.machine_id = prod.machine_id
  AND sensor.telemetry_timestamp BETWEEN prod.start_time AND prod.end_time
