config {
  type: "table",
  schema: "dev_dataform_dataset",
  name: "fct_production_performance",
  bigquery: {
    partitionBy: "production_date",
    clusterBy: ["material_id", "worker_id"]
  }
}

-- This fact table combines production orders with material and worker dimensions.
SELECT
  fact.order_id,
  fact.product_serial_no,
  fact.start_time,
  fact.end_time,
  fact.production_date,
  mat.material_id,
  wor.worker_id,
  TIMESTAMP_DIFF(fact.end_time, fact.start_time, SECOND) as production_lead_time_seconds
FROM ${ref("tmp_mes_prd_order_cleansed")} AS fact
LEFT JOIN ${ref("dim_material")} AS mat ON fact.material_id = mat.material_id
LEFT JOIN ${ref("dim_worker")} AS wor ON fact.worker_id = wor.worker_id
