config {
  type: "test",
  dataset: "fct_production_performance"
}
-- NOTE: mock data designed for deterministic JOIN results
input "tmp_mes_prd_order_cleansed" {
  SELECT 'o1' as order_id, 'psn1' as product_serial_no, 'mat1' as material_id, 'w1' as worker_id, TIMESTAMP('2023-01-01 10:00:00') as start_time, TIMESTAMP('2023-01-01 11:00:00') as end_time, DATE('2023-01-01') as production_date UNION ALL
  SELECT 'o2' as order_id, 'psn2' as product_serial_no, 'mat2' as material_id, 'w2' as worker_id, TIMESTAMP('2023-01-01 12:00:00') as start_time, TIMESTAMP('2023-01-01 14:00:00') as end_time, DATE('2023-01-01') as production_date
}
input "dim_material" {
  SELECT 'mat1' as material_id UNION ALL
  SELECT 'mat2' as material_id
}
input "dim_worker" {
  SELECT 'w1' as worker_id UNION ALL
  SELECT 'w2' as worker_id
}

SELECT
  'o1' as order_id, 'psn1' as product_serial_no, TIMESTAMP('2023-01-01 10:00:00') as start_time, TIMESTAMP('2023-01-01 11:00:00') as end_time, DATE('2023-01-01') as production_date, 'mat1' as material_id, 'w1' as worker_id, 3600 as production_lead_time_seconds
UNION ALL
SELECT
  'o2' as order_id, 'psn2' as product_serial_no, TIMESTAMP('2023-01-01 12:00:00') as start_time, TIMESTAMP('2023-01-01 14:00:00') as end_time, DATE('2023-01-01') as production_date, 'mat2' as material_id, 'w2' as worker_id, 7200 as production_lead_time_seconds
