config {
  type: "table",
  schema: "dev_dataform_dataset",
  name: "fct_production_performance",
  description: "製造実績のファクトテーブル",
  tags: ["access", "fact"],
  bigquery: {
    partitionBy: "production_date",
    clusterBy: ["material_id", "worker_id"]
  }
}

SELECT
  -- All columns from the base fact table
  prd.*,

  -- Columns from dimensions
  mat.material_name,
  wrk.worker_name,

  -- Additional calculation
  TIMESTAMP_DIFF(prd.end_time, prd.start_time, SECOND) AS production_lead_time_sec
FROM
  ${ref("tmp_mes_prd_order_cleansed")} AS prd
LEFT JOIN
  ${ref("dim_material")} AS mat ON prd.material_id = mat.material_id
LEFT JOIN
  ${ref("dim_worker")} AS wrk ON prd.worker_id = wrk.worker_id
