-- NOTE: mock data designed for deterministic JOIN results
config {
  type: "test",
  dataset: "fct_quality_inspection"
}

input "tmp_qms_inspection_std" {
  SELECT 'insp1' as inspection_id, 'psn1' as product_serial_no, DATE '2026-03-18' AS inspection_date, 5.0 as inspection_value_cm UNION ALL
  SELECT 'insp2' as inspection_id, 'psn2' as product_serial_no, DATE '2026-03-18' AS inspection_date, 6.1 as inspection_value_cm
}

input "fct_production_performance" {
  SELECT 'order1' as order_id, 'psn1' as product_serial_no, 'mat1' as material_id, 'w1' as worker_id, CAST('2026-03-17 10:00:00' AS TIMESTAMP) as start_time, CAST('2026-03-17 11:00:00' AS TIMESTAMP) as end_time, 3600 as production_lead_time_sec, 'Stainless Steel' as material_name, 'Sato Ken' as worker_name UNION ALL
  SELECT 'order2' as order_id, 'psn2' as product_serial_no, 'mat2' as material_id, 'w2' as worker_id, CAST('2026-03-17 12:00:00' AS TIMESTAMP) as start_time, CAST('2026-03-17 13:00:00' AS TIMESTAMP) as end_time, 3600 as production_lead_time_sec, 'Aluminum' as material_name, 'Tanaka' as worker_name
}

  SELECT 'insp1' as inspection_id, 'psn1' as product_serial_no, DATE '2026-03-18' AS inspection_date, 5.0 as inspection_value_cm, 'order1' as order_id, 'mat1' as material_id, 'w1' as worker_id, CAST('2026-03-17 10:00:00' AS TIMESTAMP) as production_start_time, CAST('2026-03-17 11:00:00' AS TIMESTAMP) as production_end_time, 3600 as production_lead_time_sec, 'Stainless Steel' as material_name, 'Sato Ken' as worker_name UNION ALL
  SELECT 'insp2' as inspection_id, 'psn2' as product_serial_no, DATE '2026-03-18' AS inspection_date, 6.1 as inspection_value_cm, 'order2' as order_id, 'mat2' as material_id, 'w2' as worker_id, CAST('2026-03-17 12:00:00' AS TIMESTAMP) as production_start_time, CAST('2026-03-17 13:00:00' AS TIMESTAMP) as production_end_time, 3600 as production_lead_time_sec, 'Aluminum' as material_name, 'Tanaka' as worker_name
