config {
    type: "table",
    schema: "dev_dataform_dataset",
    name: "fct_quality_inspection",
    partition_by: "inspection_date",
    cluster_by: ["product_serial_no"]
}

SELECT
    insp.*,
    prod.order_id,
    prod.start_time,
    prod.end_time,
    prod.worker_id,
    prod.material_id,
    prod.manufacturing_lead_time_sec
FROM
    ${ref("tmp_qms_inspection_std")} AS insp
LEFT JOIN
    ${ref("fct_production_performance")} AS prod
    ON insp.product_serial_no = prod.product_serial_no
