-- NOTE: mock data designed for deterministic JOIN results
config {
  type: "test",
  dataset: "fct_production_performance"
}

input "tmp_mes_prd_order_cleansed" {
  SELECT 'o1' as order_id, 'psn1' as product_serial_no, DATE('2026-03-17') as production_date, TIMESTAMP('2026-03-17 10:00:00') as start_time, TIMESTAMP('2026-03-17 11:00:00') as end_time, 'mat1' as product_id, 'w1' as worker_id UNION ALL
  SELECT 'o2' as order_id, 'psn2' as product_serial_no, DATE('2026-03-17') as production_date, TIMESTAMP('2026-03-17 12:00:00') as start_time, TIMESTAMP('2026-03-17 12:30:00') as end_time, 'mat2' as product_id, 'w2' as worker_id UNION ALL
  SELECT 'o3' as order_id, 'psn3' as product_serial_no, DATE('2026-03-18') as production_date, TIMESTAMP('2026-03-18 10:00:00') as start_time, TIMESTAMP('2026-03-18 11:15:00') as end_time, 'mat1' as product_id, 'w1' as worker_id
}

input "dim_material" {
  SELECT 'mat1' AS material_id UNION ALL
  SELECT 'mat2' AS material_id
}

input "dim_worker" {
  SELECT 'w1' AS worker_id UNION ALL
  SELECT 'w2' AS worker_id
}

SELECT 'o1' as order_id, 'psn1' as product_serial_no, DATE('2026-03-17') as production_date, TIMESTAMP('2026-03-17 10:00:00') as start_time, TIMESTAMP('2026-03-17 11:00:00') as end_time, 'mat1' as material_id, 'w1' as worker_id, 3600 as production_lead_time_sec UNION ALL
SELECT 'o2' as order_id, 'psn2' as product_serial_no, DATE('2026-03-17') as production_date, TIMESTAMP('2026-03-17 12:00:00') as start_time, TIMESTAMP('2026-03-17 12:30:00') as end_time, 'mat2' as material_id, 'w2' as worker_id, 1800 as production_lead_time_sec UNION ALL
SELECT 'o3' as order_id, 'psn3' as product_serial_no, DATE('2026-03-18') as production_date, TIMESTAMP('2026-03-18 10:00:00') as start_time, TIMESTAMP('2026-03-18 11:15:00') as end_time, 'mat1' as material_id, 'w1' as worker_id, 4500 as production_lead_time_sec
